// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llarxxxtbxczxrysvcbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsYXJ4eHh0YnhjenhyeXN2Y2J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTY5NTAsImV4cCI6MjA2Mjk5Mjk1MH0.ZYGkilksR34hCAyZ7r1OWaxIElJhyUSEz3zwJprtj5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);